var _ = require('lodash');

var people = [{
    "id": 1,
    "first_name": "Barbara",
    "last_name": "Marshall",
    "email": "bmarshall0@hexun.com",
    "gender": "Female",
    "ip_address": "166.110.30.232"
}, {
    "id": 2,
    "first_name": "Sarah",
    "last_name": "Wagner",
    "email": "swagner1@bravesites.com",
    "gender": "Female",
    "ip_address": "127.134.210.5"
}, {
    "id": 3,
    "first_name": "Ernest",
    "last_name": "Freeman",
    "email": "efreeman2@homestead.com",
    "gender": "Male",
    "ip_address": "23.80.96.15"
}, {
    "id": 4,
    "first_name": "Joyce",
    "last_name": "Marshall",
    "email": "jmarshall3@ca.gov",
    "gender": "Female",
    "ip_address": "198.46.165.62"
}, {
    "id": 5,
    "first_name": "Denise",
    "last_name": "Watson",
    "email": "dwatson4@reddit.com",
    "gender": "Female",
    "ip_address": "8.46.216.120"
}, {
    "id": 6,
    "first_name": "Janet",
    "last_name": "Gutierrez",
    "email": "jgutierrez5@hhs.gov",
    "gender": "Female",
    "ip_address": "175.129.214.232"
}, {
    "id": 7,
    "first_name": "Pamela",
    "last_name": "Woods",
    "email": "pwoods6@google.nl",
    "gender": "Female",
    "ip_address": "45.184.34.95"
}, {
    "id": 8,
    "first_name": "Deborah",
    "last_name": "Ruiz",
    "email": "druiz7@samsung.com",
    "gender": "Female",
    "ip_address": "17.238.126.240"
}, {
    "id": 9,
    "first_name": "Christopher",
    "last_name": "Elliott",
    "email": "celliott8@theguardian.com",
    "gender": "Male",
    "ip_address": "31.209.231.193"
}, {
    "id": 10,
    "first_name": "Emily",
    "last_name": "Hicks",
    "email": "ehicks9@ft.com",
    "gender": "Female",
    "ip_address": "230.163.92.29"
}, {
    "id": 11,
    "first_name": "Joe",
    "last_name": "Austin",
    "email": "jaustina@ycombinator.com",
    "gender": "Male",
    "ip_address": "13.227.212.68"
}, {
    "id": 12,
    "first_name": "Jonathan",
    "last_name": "Bowman",
    "email": "jbowmanb@tinyurl.com",
    "gender": "Male",
    "ip_address": "204.60.252.118"
}, {
    "id": 13,
    "first_name": "Marie",
    "last_name": "Carter",
    "email": "mcarterc@chicagotribune.com",
    "gender": "Female",
    "ip_address": "67.234.124.205"
}, {
    "id": 14,
    "first_name": "Jason",
    "last_name": "Patterson",
    "email": "jpattersond@biblegateway.com",
    "gender": "Male",
    "ip_address": "161.234.157.112"
}, {
    "id": 15,
    "first_name": "Linda",
    "last_name": "Baker",
    "email": "lbakere@alexa.com",
    "gender": "Female",
    "ip_address": "190.111.212.155"
}, {
    "id": 16,
    "first_name": "Kelly",
    "last_name": "Powell",
    "email": "kpowellf@msn.com",
    "gender": "Female",
    "ip_address": "117.193.253.152"
}, {
    "id": 17,
    "first_name": "Joseph",
    "last_name": "Romero",
    "email": "jromerog@un.org",
    "gender": "Male",
    "ip_address": "233.106.244.48"
}, {
    "id": 18,
    "first_name": "Janice",
    "last_name": "Payne",
    "email": "jpayneh@gravatar.com",
    "gender": "Female",
    "ip_address": "34.39.254.34"
}, {
    "id": 19,
    "first_name": "Brandon",
    "last_name": "Fuller",
    "email": "bfulleri@pinterest.com",
    "gender": "Male",
    "ip_address": "9.199.9.89"
}, {
    "id": 20,
    "first_name": "Earl",
    "last_name": "Owens",
    "email": "eowensj@census.gov",
    "gender": "Male",
    "ip_address": "218.14.157.143"
}];

var femaleCount = _.filter(people, {gender: "Female"}).length;

alert(femaleCount + " females!");

console.log("module2 stuff");
